answerDatabase = [["CITRUS-SCENTED SHOWER GEL", "Around The House"],
["RECLINING LOUNGE CHAIR", "Around The House"],
["SHAMPOO AND CONDITIONER", "Around The House"],
["ELECTRIC TOOTHBRUSH", "Around The House"],
["AFTER-SHAVE LOTION", "Around The House"],
["FISHING TACKLE BOX", "Around The House"],
["OAK CHINA CABINET", "Around The House"],
["PENS AND PENCILS", "Around The House"],
["PRUNING SHEARS", "Around The House"],
["WINDOW SCREENS", "Around The House"],
["BEANBAG CHAIR", "Around The House"],
["LINEN NAPKINS", "Around The House"],
["POLISHING WAX", "Around The House"],
["ADDRESS BOOK", "Around The House"],
["CERAMIC BOWL", "Around The House"],
["STURDY TABLE", "Around The House"],
["WOODEN TABLE", "Around The House"],
["CAPTAIN HOOK LINE AND SINKER", "Before and After"],
["WELCOME BACK TO THE FUTURE", "Before and After"],
["ULTRAVIOLET RAY ROMANO", "Before and After"],
["HOSPITAL BED IN A BAG", "Before and After"],
["WATER MAIN ATTRACTION", "Before and After"],
["EATING AN OLIVE OYL", "Before and After"],
["KNOCKOUT PUNCH BOWL", "Before and After"],
["PICK UP SPEED LIMIT", "Before and After"],
["JOE COCKER SPANIEL", "Before and After"],
["NEWS FLASH GORDON", "Before and After"],
["GENE POOL PARTY", "Before and After"],
["THE SOUTH BEACH DIET", "Book Title"],
["THE SCARLET LETTER", "Book Title"],
["THE HOUSE OF MIRTH", "Book Title"],
["THE BIG SLEEP", "Book Title"],
["CAT'S CRADLE", "Book Title"],
["A SIDE TRIP TO OXFORD UNIVERSITY", "Event"],
["SHOWS WITH SPECTACULAR STUNTS", "Event"],
["A CRUISE THROUGH GLACIER BAY", "Event"],
["ALL-EXPENSES PAID VACATION", "Event"],
["CATAMARAN SAILING CRUISE", "Event"],
["SCHOOL CHRISTMAS PAGEANT", "Event"],
["A CRUISE TO THE ISLAND", "Event"],
["SALTWATER FISHING TRIP", "Event"],
["TOURING THE WINDY CITY", "Event"],
["UNFORGETTABLE VACATION", "Event"],
["COMIC BOOK CONVENTION", "Event"],
["DARING PARACHUTE JUMP", "Event"],
["INTERNATIONAL FLIGHT", "Event"],
["LOS ANGELES MARATHON", "Event"],
["HIGH SCHOOL REUNION", "Event"],
["PRESIDENTIAL DEBATE", "Event"],
["BUSINESS CONVENTION", "Event"],
["CARIBBEAN VACATION", "Event"],
["FISHING TOURNAMENT", "Event"],
["RUNNING A MARATHON", "Event"],
["DOG DAYS OF SUMMER", "Event"],
["SIGHTSEEING CRUISE", "Event"],
["SUNNY WARM WEEKEND", "Event"],
["MARRIAGE CEREMONY", "Event"],
["SPRING WHITE SALE", "Event"],
["BOARDROOM MEETING", "Event"],
["CAMPING ROAD TRIP", "Event"],
["CARIBBEAN GETAWAY", "Event"],
["INVIGORATING WALK", "Event"],
["OCEAN-VIEW DINING", "Event"],
["WATERFRONT DINING", "Event"],
["INDEPENDENCE DAY", "Event"],
["INDEPENDENCE DAY", "Event"],
["WILD-GOOSE CHASE", "Event"],
["ACT OF CONGRESS", "Event"],
["DAZZLING SUNSET", "Event"],
["SUNNY AFTERNOON", "Event"],
["HOLIDAY WEEKEND", "Event"],
["SUMMER VACATION", "Event"],
["FAMILY REUNION", "Event"],
["HOLIDAY PARADE", "Event"],
["PIVOTAL MOMENT", "Event"],
["ANNUAL MEETING", "Event"],
["IDEAL VACATION", "Event"],
["CINCO DE MAYO", "Event"],
["CATERED PARTY", "Event"],
["FORMAL DINNER", "Event"],
["HARBOR CRUISE", "Event"],
["OPENING NIGHT", "Event"],
["HARBOR CRUISE", "Event"],
["HUMID WEATHER", "Event"],
["SAILBOAT RACE", "Event"],
["MEMORIAL DAY", "Event"],
["PRIVATE TOUR", "Event"],
["PRIVATE TOUR", "Event"],
["SPELLING BEE", "Event"],
["STATE DINNER", "Event"],
["THE INCREDIBLE HULK", "Fictional Characters"],
["THE CAT IN THE HAT", "Fictional Characters"],
["THE GREEN LANTERN", "Fictional Characters"],
["EBENEZER SCROOGE", "Fictional Characters"],
["EEYORE AND TIGGER", "Fictional Characters"],
["FRED FLINSTONE", "Fictional Characters"],
["HOMER SIMPSON", "Fictional Characters"],
["OLD KING COLE", "Fictional Characters"],
["SANTA'S ELVES", "Fictional Characters"],
["JACOB MARLEY", "Fictional Characters"],
["PASTA WITH PARMESAN CHEESE", "Food and Drink"],
["OYSTERS ON THE HALF SHELL", "Food and Drink"],
["LEMON POPPY SEED MUFFINS", "Food and Drink"],
["THOMPSON SEEDLESS GRAPES", "Food and Drink"],
["AMERICAN CHEDDAR CHEESE", "Food and Drink"],
["CREAMY RICOTTA CHEESE", "Food and Drink"],
["FRESH PINEAPPLE JUICE", "Food and Drink"],
["FRIED SEAFOOD PLATTER", "Food and Drink"],
["PEPPERMINT CANDY CANE", "Food and Drink"],
["LEMON-GARLIC CHICKEN", "Food and Drink"],
["SAUSAGE AND POTATOES", "Food and Drink"],
["SPICY COCKTAIL SAUCE", "Food and Drink"],
["BAKED FRUIT COMPOTE", "Food and Drink"],
["CHICKEN QUESADILLAS", "Food and Drink"],
["DEEP-DISH PEACH PIE", "Food and Drink"],
["FRESH FRUIT PLATTER", "Food and Drink"],
["GRANDMA'S FRUITCAKE", "Food and Drink"],
["ORGANIC BRAZIL NUTS", "Food and Drink"],
["POACHED PARED FRUIT", "Food and Drink"],
["SEEDLESS WATERMELON", "Food and Drink"],
["TUNA SALAD SANDWICH", "Food and Drink"],
["YELLOW BELL PEPPERS", "Food and Drink"],
["BUTTERHEAD LETTUCE", "Food and Drink"],
["GREEN CORN TAMALES", "Food and Drink"],
["MILK CHOCOLATE BAR", "Food and Drink"],
["OVEN-FRIED CHICKEN", "Food and Drink"],
["SEAFOOD TETRAZZINI", "Food and Drink"],
["BEANS AND CORNBREAD", "Food and Drink"],
["CELERY ROOT SALAD", "Food and Drink"],
["DELICIOUS CUISINE", "Food and Drink"],
["GREEN TURTLE SOUP", "Food and Drink"],
["CHOCOLATE TOFFEE", "Food and Drink"],
["CHOCOLATE MOUSSE", "Food and Drink"],
["HUEVOS RANCHEROS", "Food and Drink"],
["SALAD VEGETABLES", "Food and Drink"],
["THIN-CRUST PIZZA", "Food and Drink"],
["TEA AND CRUMPETS", "Food and Drink"],
["CHOCOLATE SYRUP", "Food and Drink"],
["DEEP-DISH PIZZA", "Food and Drink"],
["JUICY PINEAPPLE", "Food and Drink"],
["LIVER DUMPLINGS", "Food and Drink"],
["RED VELVET CAKE", "Food and Drink"],
["SKINNED TANGELO", "Food and Drink"],
["VEGETABLE JUICE", "Food and Drink"],
["BAGLES AND LOX", "Food and Drink"],
["BUFFALO BURGER", "Food and Drink"],
["ENGLISH TOFFEE", "Food and Drink"],
["FRESH PARSNIPS", "Food and Drink"],
["FRUIT COCKTAIL", "Food and Drink"],
["HOMEMADE PASTA", "Food and Drink"],
["HABANERO SAUCE", "Food and Drink"],
["NACHOS SUPREME", "Food and Drink"],
["SHEPHERD'S PIE", "Food and Drink"],
["VEGETABLE SOUP", "Food and Drink"],
["BOTTLED WATER", "Food and Drink"],
["CHICKEN SALAD", "Food and Drink"],
["DELI SANDWICH", "Food and Drink"],
["HAWAIIN FEAST", "Food and Drink"],
["MINCEMEAT PIE", "Food and Drink"],
["RIPE BANANA'S", "Food and Drink"],
["BASIL LEAVES", "Food and Drink"],
["CHEESE PIZZA", "Food and Drink"],
["FRENCH FRIES", "Food and Drink"],
["KEY LIME PIE", "Food and Drink"],
["SMOKED TROUT", "Food and Drink"],
["WEDDING CAKE", "Food and Drink"],
["AFTERSCHOOL ACTIVITIES", "Fun and Games"],
["CROSS-COUNTRY SKIING", "Fun and Games"],
["KNIGHT BISHOP AND PAWN", "Fun and Games"],
["PLAYING ICE HOCKEY", "Fun and Games"],
["A DIP IN THE POOL", "Fun and Games"],
["MOVIE STUDIO TOUR", "Fun and Games"],
["PLAYING STICKBALL", "Fun and Games"],
["CATHCHING A WAVE", "Fun and Games"],
["BALLOON ANIMALS", "Fun and Games"],
["THUMB WRESTLING", "Fun and Games"],
["ARM WRESTLING", "Fun and Games"],
["BELLY DANCING", "Fun and Games"],
["MODELING CLAY", "Fun and Games"],
["ROCK CLIMBING", "Fun and Games"],
["SLOT MACHINE", "Fun and Games"],
["TROLLEY TOUR", "Fun and Games"],
["LEMON AND LIME SQUEEZER", "in The Kitchen"],
["ALUMINUM CHEESE GRATER", "in The Kitchen"],
["CONVENTIONAL OVEN", "in The Kitchen"],
["CONICAL STRAINER", "in The Kitchen"],
["INSULATED TEAPOT", "in The Kitchen"],
["DRINKING STRAWS", "in The Kitchen"],
["CANNED GOODS", "in The Kitchen"],
["GREAT SAND DUNES NATIONAL PARK", "Landmark"],
["UNIVERSAL STUDIOS HOLLYWOOD", "Landmark"],
["NATIONAL GALLERY OF ART", "Landmark"],
["MADISON SQUARE GARDEN", "Landmark"],
["RADIO CITY MUSIC HALL", "Landmark"],
["BUNKER HILL MONUMENT", "Landmark"],
["DENALI NATIONAL PARK", "Landmark"],
["THE CAPITOL ROTUNDA", "Landmark"],
["THE CHURCHILL HOTEL", "Landmark"],
["NATIONAL ARBORETUM", "Landmark"],
["ST. PETER'S SQUARE", "Landmark"],
["STATUE OF LIBERTY", "Landmark"],
["WALT DISNEY WORLD", "Landmark"],
["WESTMINSTER ABBEY", "Landmark"],
["JUDICIARY SQUARE", "Landmark"],
["THE GETTY CENTER", "Landmark"],
["ARLINGTON HOUSE", "Landmark"],
["LIBERACE MUSEUM", "Landmark"],
["LUXOR'S PYRAMID", "Landmark"],
["MEMORIAL BRIDGE", "Landmark"],
["FREMONT STREET", "Landmark"],
["CIRCUS CIRCUS", "Landmark"],
["NATIONAL MALL", "Landmark"],
["PRAGUE CASTLE", "Landmark"],
["CAPITOL HILL", "Landmark"],
["MUSCLE BEACH", "Landmark"],
["PENN STATION", "Landmark"],
["LONG-LEGGED FLAMINGO", "Living Thing"],
["AUSTRALIAN SHEPHERD", "Living Thing"],
["MINIATURE SCHNAUZER", "Living Thing"],
["AMERICAN ALLIGATOR", "Living Thing"],
["GREAT WHITE SHARK", "Living Thing"],
["AFRICAN ELEPHANT", "Living Thing"],
["EELS AND STINGRAYS", "Living Thing"],
["CHERRY BLOSSOMS", "Living Thing"],
["GIANT SCHNAUZER", "Living Thing"],
["MOOSE AND CARIBOU", "Living Thing"],
["SQUIRREL MONKEY", "Living Thing"],
["AFRICAN VIOLET", "Living Thing"],
["BORDER TERRIER", "Living Thing"],
["EVERGREEN TREE", "Living Thing"],
["SIBERIAN HUSKY", "Living Thing"],
["TALL ELM TREES", "Living Thing"],
["THE FAMILY PET", "Living Thing"],
["CHOCOLATE LAB", "Living Thing"],
["THE TALENTED MR. RIPLEY", "Movie Title"],
["AN AMERICAN IN PARIS", "Movie Title"],
["BACK TO THE FUTURE", "Movie Title"],
["PLANET OF THE APES", "Movie Title"],
["A BEAUTIFUL MIND", "Movie Title"],
["THE DIRTY DOZEN", "Movie Title"],
["ANGELS AND DEMONS", "Movie Title"],
["SOUTH PACIFIC", "Movie Title"],
["ALL ABOUT EVE", "Movie Title"],
["CITY SLICKERS", "Movie Title"],
["DRIVING INSTRUCTOR", "Occupation"],
["RECREATION WORKER", "Occupation"],
["ATTORNEY GENERAL", "Occupation"],
["PERSONAL TRAINER", "Occupation"],
["PUBLIC DEFENDER", "Occupation"],
["COURT REPORTER", "Occupation"],
["BRAIN SURGEON", "Occupation"],
["MUSIC TEACHER", "Occupation"],
["BUFFALO NATIONAL RIVER", "On The Map"],
["FAIRBANKS AND KETCHIKAN", "On The Map"],
["THE CITY OF CAMBRIDGE", "On The Map"],
["NEW BRUNSWICK CANADA", "On The Map"],
["SAINT LAWRENCE RIVER", "On The Map"],
["SOUTHEASTERN FLORIDA", "On The Map"],
["ALLEGHENY MOUNTAINS", "On The Map"],
["BOULDER CITY NEVADA", "On The Map"],
["GREENLAND AND ICELAND", "On The Map"],
["LOUISVILLE KENTUCKY", "On The Map"],
["PENNSYLVANIA AVENUE", "On The Map"],
["MONTGOMERY ALABAMA", "On The Map"],
["SEATTLE WASHINGTON", "On The Map"],
["NEWARK NEW JERSEY", "On The Map"],
["BRITISH COLUMBIA", "On The Map"],
["FAIRBANKS ALASKA", "On The Map"],
["SUNNY CALIFORNIA", "On The Map"],
["ALBANY NEW YORK", "On The Map"],
["CAPITAL BELTWAY", "On The Map"],
["DENVER COLORADO", "On The Map"],
["LOWER MANHATTAN", "On The Map"],
["NANTUCKET SOUND", "On The Map"],
["PORTLAND OREDON", "On The Map"],
["UPPER WEST SIDE", "On The Map"],
["HAIGHT-ASHBURY", "On The Map"],
["LAKE MICHIGAN", "On The Map"],
["NEW YORK CITY", "On The Map"],
["TAMPA FLORIDA", "On The Map"],
["OTTAWA CANADA", "On The Map"],
["POTOMAC RIVER", "On The Map"],
["HARLEM RIVER", "On The Map"],
["PADRE ISLAND", "On The Map"],
["TIMES SQUARE", "On The Map"],
["VENICE ITALY", "On The Map"],
["OFFENSIVE AND DEFENSIVE PLAYERS", "People"],
["NOTRE DAME'S FIGHTING IRISH", "People"],
["FRIENDS IN HIGH PLACES", "People"],
["VOLUNTEER FIREFIGHTERS", "People"],
["ARCHBISHOP AND CARDINAL", "People"],
["PROFESSIONAL SURFERS", "People"],
["FULL-TIME EMPLOYEES", "People"],
["AQUARIANS AND VIRGOS", "People"],
["AIRLINE PASSENGERS", "People"],
["RELIABLE WITNESSES", "People"],
["FEDERAL EMPLOYEES", "People"],
["HOLLYWOOD LEGENDS", "People"],
["SINGERS AND DANCERS", "People"],
["VOLUNTEER FIREMEN", "People"],
["AMATUER ATHLETES", "People"],
["SMILING CHILDREN", "People"],
["ABSENTEE VOTERS", "People"],
["CELEBRITY CHEFS", "People"],
["COLLEGE BUDDIES", "People"],
["FRIENDLY LOCALS", "People"],
["FLYING ACROBATS", "People"],
["ROOTING SECTION", "People"],
["SOCIAL CLIMBERS", "People"],
["TARGET AUDIENCE", "People"],
["AWARD NOMINEES", "People"],
["COMMANDO SQUAD", "People"],
["STRING QUARTET", "People"],
["YOUNG HOPEFULS", "People"],
["BRIDE AND GROOM", "People"],
["SUPREME COURT", "People"],
["UPPER ECHELON", "People"],
["ADORING FANS", "People"],
["COLONIAL HISTORY BUFF", "Person"],
["CERTIFIED TECHNICIAN", "Person"],
["SPEAKER OF THE HOUSE", "Person"],
["DADDY'S LITTLE GIRL", "Person"],
["LONGTIME SUBSCRIBER", "Person"],
["JOURNALISM STUDENT", "Person"],
["BICYCLE MESSENGER", "Person"],
["COCKTAIL WAITRESS", "Person"],
["GOLD MEDAL WINNER", "Person"],
["CAMPAIGN MANAGER", "Person"],
["GREAT GRANDCHILD", "Person"],
["JUNIOR LIFEGUARD", "Person"],
["SCHOOL COUNSELOR", "Person"],
["STEADY BOYFRIEND", "Person"],
["DOUBTING THOMAS", "Person"],
["GRAFFITI ARTIST", "Person"],
["MATRON OF HONOR", "Person"],
["NATURAL REDHEAD", "Person"],
["OLYPMIC SWIMMER", "Person"],
["SENIOR OFFICIAL", "Person"],
["TRAINED ATHLETE", "Person"],
["CHIEF OF STAFF", "Person"],
["CIVIL WAR BUFF", "Person"],
["JACKPOT WINNER", "Person"],
["JUNIOR SENATOR", "Person"],
["MEDICAL DOCTOR", "Person"],
["PLATOON LEADER", "Person"],
["PUBLIC SPEAKER", "Person"],
["STAR PERFORMER", "Person"],
["EXPERT ARCHER", "Person"],
["FIRST BASEMAN", "Person"],
["LEFT FIELDER", "Person"],
["STAGE MOTHER", "Person"]]
